src/top.sv
src/rtl/core.sv
src/rtl/decode/decode.sv
src/rtl/exe/exe.sv
src/rtl/fetch/fetch.sv
src/rtl/globals/gprs.sv
src/rtl/globals/scoreboard.sv
src/rtl/icache/icache.sv
src/rtl/mem/mem.sv
src/rtl/regrd/regrd.sv
src/rtl/retire/retire.sv
